export const GET_ALL_BOOKS = 'GET_ALL_BOOKS'
export const GET_MY_BOOKS = 'GET_MY_BOOKS'
export const GET_QUICK_RECOMM = 'GET_QUICK_RECOMM'
export const ADD_BOOK = 'ADD_BOOK'

export const GET_SETTINGS = 'GET_SETTINGS'
export const GET_USER_RECOMMENDATIONS = 'GET_USER_RECOMMENDATIONS'

